### ISSUE TITLE
unexpected newline

### ISSUE THREAD

**Issue by xfgavin** [metrumresearchgroup/gridengine_prometheus#17]
I built a docker imaging using trunk version and got this error when executing the compiled binary.
/go/src/metrumresearchgroup/gridengine_prometheus # /go/bin/gridengine_exporter
/go/bin/gridengine_exporter: line 2: syntax error: unexpected newline

**Comment by shairozan** [comment]
Did you mean the master branch? If you can provide the dockerfile you're using I can try building and see what's going on. Also what platform are you targeting the docker deployment for? Windows/Linux?

**Comment by xfgavin** [comment]
Thanks, I used the dockerfile in master branch, but commented out entrypoint. I built my docker image in a vmware linux guest OS.  No error was seen during the build process.

I am going to use it in Linux.

**Comment by shairozan** [comment]
Try [this dockerfile](https://github.com/metrumresearchgroup/gridengine_prometheus/blob/issue/invalid_dockerfile/Dockerfile)

it's a branch I just created the deal with the issue. The dockerfile was old and built before go mod was used in the project. I can build and execute here, so you should be good to go to at least get started. 

If this gets you past the newline error, let me know and I'll merge up to master.

**Comment by xfgavin** [comment]
It's working, Thanks.

**Comment by shairozan** [comment]
merged into master.
