### ISSUE TITLE
Error when extracting resources

### ISSUE THREAD

**Issue by dohnto** [metrumresearchgroup/gridengine_prometheus#2]
I guess that this problem is in underlying library gogridengine (or my setup), but I will raise an issue here since the problem comes up when running exporter.

Commit: ed147025835a63f6b6d34e4d6c9b6cc2174cc57e

When running exporter and scraping it, I see following errors: 
```
ERRO[0002] There was an error extracting Free Memory from the resource list  error="Could not located the requested key"
ERRO[0002] There was an error extracting Used Memory from the resource list  error="Could not located the requested key"
ERRO[0002] There was an error extracting CPU Utilization from the resource list  error="Could not located the requested key"
ERRO[0002] There was an error extracting Free Memory from the resource list  error="Could not located the requested key"
ERRO[0002] There was an error extracting Used Memory from the resource list  error="Could not located the requested key"
ERRO[0002] There was an error extracting CPU Utilization from the resource list  error="Could not located the requested key"
```

I guess that the xml cannot be parsed. From code I see, that the xml is gained using `qstat -u * -F -xml`. 

Here is my snippet of running this command. Note that most of the xml is omitted.
```xml
<?xml version='1.0'?>
<job_info  xmlns:xsd="http://gridengine.sunsource.net/source/browse/*checkout*/gridengine/source/dist/util/resources/schemas/qstat/qstat.xsd?revision=1.11">
  <queue_info>
    <Queue-List>
      ...
      <resource name="mem_free" type="hl">0.0G</resource>
      ...
    </Queue-List>
...
```

Is somehow my settings wrong? Thanks for any help.

**Comment by shairozan** [comment]
So the first thing to check is:

- How are you running the exporter? If you're running it as a service, try running it just as your own user and scraping This will tell us if the variables needed for the service need to be updated. 
- If you're deploying it as a service, the /etc/default/gridengine_prometheus file will need to be updated with the variables you'll need to access it. 

In the meantime I'll dig down into the gogridengine to see what may cause that error. Would it be possible for you to redact the XML and provide it? Then I can manually run it through the engine to make sure that there's no differences in the schemas I should accomodate.

**Comment by shairozan** [comment]
And it doesn't look like it's an issue with the underlying method, shy of just not being able to serialize the data at all. The error that's coming back is supposed to show up when we look for a key we can't find. In this case, the prometheus exporter is trying to find the `mem_free` key resource, which is obviously in the output. I think the best path would be let's try running the exporter as you in an active shell and access the endpoint to see if it scraped. If it did, we probably just need to mess with your env variables.

**Comment by dohnto** [comment]
> How are you running the exporter? If you're running it as a service, try running it just as your own user and scraping This will tell us if the variables needed for the service need to be updated.

Since I cannot found any documentation about running, I assumed:
```sh
./grid &
curl localhost:9081/metrics
```

Also when I look at https://github.com/metrumresearchgroup/gridengine_prometheus/blob/master/scripts/environment.file#L1 There seem to be `/data/home/darrellb/` in `PATH` which I think is related to your custom environment :)

**Comment by dohnto** [comment]
I was able to move forward and I dont see errors above (probably temporary, I believe that when particular jobs will be queued, they the errors will appear again).

Now, when I manually scrape, I get following error:

```
curl localhost:9081/metrics

An error has occurred while serving metrics:

142 error(s) occurred:
* collected metric "job_state_value" { label:<name:"hostname" value:"abc123" > label:<name:"job_number" value:"595406" > label:<name:"name" value:"xyz" > label:<name:"owner" value:"me" > gauge:<value:1 > } was collected before with the same name and label values
...
```

When I examine the xml generated by **qstat** I can really see:

```xml
...
      <job_list state="running">
        <JB_job_number>595406</JB_job_number>
        <JAT_prio>2.50000</JAT_prio>
        <JB_name>xyz</JB_name>
        <JB_owner>me</JB_owner>
        <state>r</state>
        <JAT_start_time>2019-11-14T16:26:28</JAT_start_time>
        <slots>1</slots>
        <tasks>1</tasks>
      </job_list>
      <job_list state="running">
        <JB_job_number>595406</JB_job_number>
        <JAT_prio>2.50000</JAT_prio>
        <JB_name>xyz</JB_name>
        <JB_owner>me</JB_owner>
        <state>r</state>
        <JAT_start_time>2019-11-14T16:26:28</JAT_start_time>
        <slots>1</slots>
        <tasks>3</tasks>
      </job_list>
...
```
Does that help? I seems that in our setup **job number** + **job_name** **job_owner** is not unique as you expect in the code. Is that correct?

Note, that these errors apply for following metrics:
* free_memory_bytes
* job_priority_value
* job_slots_count
* job_state_value
* reserved_slots_count
* sge_cpu_utilization_percent
* sge_load_average
* sge_total_memory_bytes
* sge_used_memory_bytes
* total_slots_count
* used_slots_count

**Comment by shairozan** [comment]
We are expecting some degree of uniqueness for the job number / owner as they're being used as prometheus labels. What's happening is in the `processJobs` method is looking at all of the jobs loaded from the underlying library, and iterating over them to generate metrics specifying the hostname / number et all as labels. The first one processes fine, but once the second _similar_ metric hits it, it panics.

At this point in the process, the remainder of the metrics should have processed, however. Can you verify your hostnames are all different as well? That's the only thing I can think that would trigger the similar message during the SGE_* evaluation. We're basically taking the hostname and using it as a label. I can see that we may need to loosen that up to take the entire hostname to relieve that though. Can you provide a sample of the hostname? Even if redacted? The only samples we had were for our hosts, so I want to make sure I can accomodate other structures

**Comment by dohnto** [comment]
I think that the problem is with [task id](https://arc.leeds.ac.uk/using-the-systems/why-have-a-scheduler/advanced-sge-task-arrays/) which is not exposed in your metrics and cause the duplication.

**Comment by shairozan** [comment]
You are indeed correct. I can see the content after playing around with task array submission:

```xml   
      <job_list state="running">
        <JB_job_number>1006</JB_job_number>
        <JAT_prio>0.55500</JAT_prio>
        <JB_name>task_array.sh</JB_name>
        <JB_owner>darrellb</JB_owner>
        <state>r</state>
        <JAT_start_time>2019-11-15T11:31:47</JAT_start_time>
        <slots>1</slots>
        <tasks>37</tasks>
      </job_list>
```

I'll need to update the underlying gogridengine to support the new field for serialization, and then also add it as an exporter component label. Even when it's not present it'll still default to 0, but in those cases as long as job number etc are unique shouldn't generate issues. I'll tag you on the PR there and let you know when I have the PR ready for the exporter.

**Comment by shairozan** [comment]
@dohnto Hey, I just got the task changes merged into the core library. What we're doing is two fold:

1. We're custom serializing the "tasks" object into go as both a string and int64 value.
2. If there's a pending job, we look for the task range definition in he string 
3. If present, we literally extrapolate those out into actual job objects with the individual task IDs. 

That way when you look at it from a metric perspective, the tasks are all still individually counted as pending, so Prometheus can give an accurate representation of scheduled / unscheduled work. 

I've got to create a branch here now to use the new version of the library and add a label to the objects. We'll add the task ID after the job number as a label, which will be 0 in most non task array scenarios, but will provide the uniqueness required to satisfy prometheus' labeling concerns.

**Comment by dohnto** [comment]
@shairozan Thank you for explaining me. When your branch is ready, let me know so I can test in our environment.

**Comment by shairozan** [comment]
Hey @dohnto , I've got a tasks branch that implements the changes in the library and adds the task ID. Can you try [this binary](https://drive.google.com/file/d/1_vSnYHdXJSwu21T3kK7IvOxRawAuzcFR/view?usp=sharing) and see if it works for you? It's built for linux AMD64. Let me know if you need any other arch / platform

Once it looks like it's working, I'll merge the branches and do a new release. I've run it on an instance locally and task extrapolation looks to be working fine

**Comment by dohnto** [comment]
@shairozan Thank you. I tried the version from `tasks` branch. I think it helped but...

I still got:
```
An error has occurred while serving metrics:

112 error(s) occurred:
* collected metric "used_slots_count" { label:<name:"hostname" value:"hostname1" > gauge:<value:4 > } was collected before with the same name and label values
...
```

I think this is caused since our qstat output contains:
```xml
    <Queue-List>
      <name>cpu2.q@hostname1</name>
      ....
    </Queue-List>
    <Queue-List>
      <name>gpu.q@hostname1</name>
      ....
    </Queue-List>
```
As I can [see](https://github.com/metrumresearchgroup/gridengine_prometheus/blob/tasks/grid.go#L130), you are ignoring everyting before the `@` which causes hostname collision.

**Comment by shairozan** [comment]
Aaah that's an easy fix thankfully. All the samples I had only had the one queue per host. Let me work on getting that done for you and we may be good to go.

**Comment by dohnto** [comment]
Hi, have you found time to progress with this? Can I help with it or you are nearly there?

**Comment by shairozan** [comment]
Hey there. Sorry I haven't been able to work on it because of the holidays, but I'll work on it tonight. It's a relatively simple change, so it shouldn't take too long. I'll upload another linux binary for you to try

**Comment by shairozan** [comment]
Try [this one](https://drive.google.com/file/d/1PdO1Z3R1SzCLrBuY5no6DmSBCu7oVn2a/view?usp=sharing) and let me know if it works. We're just collecting the full hostname at this point.

**Comment by dohnto** [comment]
Can I please ask you for a branch/code instead of a binary?

**Comment by shairozan** [comment]
Hey the source is already in a branch called tasks. You can build it from there however you need.

**Comment by dohnto** [comment]
It says:

> Latest commit 45b676b 10 days ago

The commit seems to fix the task ID not, the hostname. I have already tried to build from this commit few 9 days ago.

Are you sure, that you pushed your changes? :)

**Comment by shairozan** [comment]
Hey sorry I did forget to push the changes. I've been traveling the last few days. Just pushed it :-D

**Comment by dohnto** [comment]
Thanks. It is better, now I can scrape metrics, but there are only go/prometheus related metrics.

On server I can see error:
```
ERRO[0171] Attempting to parse Task identifier failed: strconv.ParseInt: parsing "1,4": invalid syntax 
ERRO[0171] Unable to marshal the XML cleanly into an object  error="strconv.ParseInt: parsing \"1,4\": invalid syntax"
```

In qstat output I see
```xml
    <job_list state="pending">
      <JB_job_number>619547</JB_job_number>
      <JAT_prio>3.50000</JAT_prio>
      <JB_name>aaa.sh</JB_name>
      <JB_owner>bbb</JB_owner>
      <state>Eqw</state>
      <JB_submission_time>2019-12-07T18:29:19</JB_submission_time>
      <slots>1</slots>
      <tasks>1,4</tasks>
    </job_list>
```

**Comment by shairozan** [comment]
Ugh it's because of yet another string representation of a task. 

` <tasks>1,4</tasks>` didn't come up when I ran tasks locally. Just the format of "1-6:1" 

I'll have to update it to look for both formats and extrapolate both

**Comment by dohnto** [comment]
Hi @shairozan is there something I can help with? Should I dig into the `gogridengine` and try to fix it myself?

**Comment by shairozan** [comment]
You can try to, but I'm about to get back onto it. Had to work on some other projects. Basically what's happening is that, from the previous samples we saw one text representation of task ids, which indicated a range. Apparently they're also grouped as you mentioned above:

`<tasks>1,4</tasks>`

There's a section of code where we extrapolated the ranges out from the value in tasks, but we'll also need to look for this structure

**Comment by shairozan** [comment]
The tasks branch has been updated to include changes from the tasks branch of the gogridengine. It'll extrapolate task ranges as well as task groups. Try it now and let's see how it goes.

**Comment by dohnto** [comment]
@shairozan It seems to be working, thanks!

**Comment by dohnto** [comment]
After using it and creating some dashboard I have found several bugs/issues/features. We can create new issues or we can discuss it here.

 ##  job_state_value

This metrics hides real state of the job/task. Why not to use something like enum:
```
job_state{job_id="123", state="r", ...}      1
job_state{job_id="123", state="qw", ...}     0
...
```

There is additional problem, and that is when you count running jobs
```
count(job_state_value{} == 1)
```
and that is [staleness issue](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness) which causes, that number of running jobs is reported higher than it should be.

stavy jobu by meli byt labels, uvest vsechny stavy

## pending jobs
If there is a pending job, there is reported only 1 task
```
job_state_value{hostname="hostname",job_number="62752",name="test.sh",owner="user",task_id="0"} 0
```
although there are multiple tasks queued. I can provide xml example if needed.

## [feature] queue label

ATM, queue is part of hostname and `label_replace` must be used. It would be cool to have 2 separate labels: `queue`, `hostname`.

## sge_cpu_utilization_percent
This metric is created based on `cpu` resource in xml. I couldn't find documentation to it, can you please elaborate why this is percentage or link me to a docs/source code?

**Comment by dohnto** [comment]
Anyway, thank you for this. Should we create separate issues for this? The only think that is blocking from merging `tasks` branch is the first the issues.

**Comment by shairozan** [comment]
These should be separate issues and none of these block merging the tasks branch. The original issue was opened because there were errors generated during export because of the inability to process task arrays. That has been fixed, this branch will go through code review and be merged in.

**Comment by dohnto** [comment]
Understood. Thanks

**Comment by shairozan** [comment]
Also regarding the percentage, I also haven't been able to find a concrete definitions. It's a resource typed as a DOUBLE, but I've never seen it above 1, so the assumption was that, since load was already expressed, that it was an expression of CPU % utilization. Could be wrong, just haven't seen anything to support otherwise. I've already created some other other issues as well to get them started.
