### ISSUE TITLE
ERRO[0004] There was an error processing the XML output  error="exit status 1"

### ISSUE THREAD

**Issue by tfhartmann** [metrumresearchgroup/gridengine_prometheus#30]
Hi, Is this project still maintained?

**Comment by shairozan** [comment]
There are people who utilize the code yes, we just haven't had to make changes to it for a while since the grid engine hasn't changed.

**Comment by tfhartmann** [comment]
That's exciting news! We'd love to use this exporter, but I'm having some trouble with it, and was hoping I could ask folks for help. Any help or guidance would be very much appreciated!    

I've been having a problem with the exporter that has me a bit stumped.  I think the config is correct, I've installed the RPM from the artifacts here on the repo, and we use Grid Engine 8.5.5.   The service starts up ok, but when I browse to the metrics page, I get the below error in debug mode. At first I thought it was an issue with the path not being set correctly but running the process in `strace`  I do see the correct path 
`newfstatat(AT_FDCWD, "/broad/uge/8.5.5/bin/lx-amd64/qstat", {st_mode=S_IFREG|0755, st_size=3408026, ...}, 0) = 0`


here's how I'm running the command: 

`/usr/local/bin/gridengine_prometheus --debug --config /etc/gridengine_prometheus/config.yaml` 

The and the error I'm seeing. 

```
Config:
map[string]interface {}{"pidfile":"/var/run/gridengine_prometheus.pid", "port":9081, "sge":map[string]interface {}{"arch":"lx-amd64", "cell":"devuger", "cluster_name":"devuger-855", "execd_port":6655, "qmaster_port":6654, "root":"/broad/uge/8.5.5"}, "test":false}
Defaults:
map[string]interface {}{}
INFO[0000] Getting ready to start exporter on port 9081


ERRO[0005] An error occurred during execution of the requested binary: exit status 1
ERRO[0005] There was an error processing the XML output  error="exit status 1"
```

**Comment by tfhartmann** [comment]
> There are people who utilize the code yes, we just haven't had to make changes to it for a while since the grid engine hasn't changed.

@shairozan  If you have any bandwidth to point me in the right direction, It would be a huge help!

**Comment by tfhartmann** [comment]
*bump*

**Comment by shairozan** [comment]
Got it, sorry I missed this earlier. Can you provide the path to `qstat` and let's make sure it's configured in the gridengine configuration

**Comment by tfhartmann** [comment]
@shairozan  Thanks for the help!  Our path to `qstat` is `/broad/uge/8.5.5/bin/lx-amd64/qstat`   and running `qstat -u * -F -xml`  returns output i'd expect.  

the I believe I've set out config file correctly, here's the output of both my env, and the config.yaml file that the export is loading 

```
SGE_CELL=devuger
SGE_EXECD_PORT=6655
SGE_QMASTER_PORT=6654
SGE_ROOT=/broad/uge/8.5.5
SGE_CLUSTER_NAME=devuger-855
```

and config.yaml 

```
test: false
port: 9081
pidfile: "/var/run/gridengine_prometheus.pid"
sge:
  arch: "lx-amd64"
  cell: devuger
  execd_port: 6655
  qmaster_port: 6654
  root: /broad/uge/8.5.5
  cluster_name: "devuger-855"
```

**Comment by shairozan** [comment]
Couple of questions as follow up:

Are you starting this as a systemd unit or a sysv init script? The underlying library that the prometheus handler uses, the go grid serializer, essentially just looks for `qstat` to be in path:

```go
binary, err := exec.LookPath("qstat")
```

This is probably where it's failing. The configuration variables look correct for _once qstat_ can be called, but I think you'll need to set the `PATH` environment variable in the systemd unit file or the sysv init script. I can take a stab at helping out if you can post whatever you have redacting your private information

**Comment by tfhartmann** [comment]
We are using the systemd unit examples from this [RPM](https://github.com/metrumresearchgroup/gridengine_prometheus/releases/download/v0.1.13/gridengine_prometheus_linux_amd64.rpm)   

Right now, I think the unit file is basically the same as one shipped with the RPM, should I be passing in the `SGE_ROOT` into path, or the complete path to qstat?  Or `SGE_ROOT/bin/<arch>` ?

**Comment by shairozan** [comment]
Based on your input, you may want to try updating the systemd unit file to the below:

```ini
[Unit]
Description=gridengine_prometheus

[Service]
Type=simple
Restart=always
RestartSec=5s
ExecStart=/usr/local/bin/gridengine_prometheus --config /etc/gridengine_prometheus/config.yaml
Environment=PATH=/broad/uge/8.5.5/bin/lx-amd64

[Install]
WantedBy=multi-user.target%
```

We set the environment path explicitly to where you mentioned `qstat` is located. Try:

1. Changing the unit to the above
2. `sudo systemctl daemon-reload`
3. `sudo systemctl restart gridengine_prometheus`

When the exporter starts again it should _explicitly_ have a path specified, which means the `LookPath` function should find it

**Comment by tfhartmann** [comment]
:hmm:  Sadly that didn't help 😢   I still get the same error messages 

```
Nov 21 13:59:45 hostname.example.org systemd[1]: Started gridengine_prometheus.
Nov 21 13:59:45 hostname.example.org gridengine_prometheus[27628]: time="2023-11-21T13:59:45Z" level=info msg="Getting ready to start exporter on port 9081"
Nov 21 13:59:59 hostname.example.org gridengine_prometheus[27628]: time="2023-11-21T13:59:59Z" level=error msg="An error occurred during execution of the requested binary: exit status 1"
Nov 21 13:59:59 hostname.example.org gridengine_prometheus[27628]: time="2023-11-21T13:59:59Z" level=error msg="There was an error processing the XML output" error="exit status 1"
```

**Comment by tfhartmann** [comment]
*bumping after the holiday in the USA*

**Comment by shairozan** [comment]
Can you provide the XML output from `qstat -F -xml` ? It's complaining about not being able to serialize the output, so I can try to marshal it manually and see what's not working. If that doesn't work we'll look at cutting a branch to provide more details for you to try working with

**Comment by tfhartmann** [comment]
> Can you provide the XML output from `qstat -F -xml` ? It's complaining about not being able to serialize the output, so I can try to marshal it manually and see what's not working. If that doesn't work we'll look at cutting a branch to provide more details for you to try working with

Thanks for all the help! 
Added the output to this [gist](https://gist.github.com/tfhartmann/55b806f398ad226ec2c3a7cd5017cedf)

**Comment by shairozan** [comment]
So I verified the XML provided marshals fine back into the expected structs. Going to update the underlying library (gogridengine) and then this to provide more information. I'll have to extract the stdErr etc from the execution to provide that in logging for the exporter so that we can get a better idea of what's happening

**Comment by tfhartmann** [comment]
> So I verified the XML provided marshals fine back into the expected structs. Going to update the underlying library (gogridengine) and then this to provide more information. I'll have to extract the stdErr etc from the execution to provide that in logging for the exporter so that we can get a better idea of what's happening

Cool, let me know if there's a branch I should build off, and I'll give it a whirl!

**Comment by tfhartmann** [comment]
@shairozan I wanted to bump this to see if you'd had any time to work on the `gogridengine` lib?  I know in the 🇺🇸  we are running into the holidays, so appreciate that time may be in short supply :)

**Comment by shairozan** [comment]
Hey @tfhartmann not yet, but I haven't forgotten about it. It's still on my list. Hoping to get to it this week and at least potentially have a build we can test to get some more information from what's failing execution

**Comment by tfhartmann** [comment]
> Hey @tfhartmann not yet, but I haven't forgotten about it. It's still on my list. Hoping to get to it this week and at least potentially have a build we can test to get some more information from what's failing execution

Awesome! Thanks for the heads-up!

**Comment by shairozan** [comment]
@tfhartmann Hey there. I've got a release candidate out: 
https://github.com/metrumresearchgroup/gridengine_prometheus/releases/tag/v0.0.14-rc2

This basically uses a newer version of the lower library that both wraps and logs combined execution output. Try this binary and we should get more details rather than exit status 1

**Comment by tfhartmann** [comment]
> @tfhartmann Hey there. I've got a release candidate out: https://github.com/metrumresearchgroup/gridengine_prometheus/releases/tag/v0.0.14-rc2
> 
> This basically uses a newer version of the lower library that both wraps and logs combined execution output. Try this binary and we should get more details rather than exit status 1

Awesome! I'll give it a try ASAP!

**Comment by tfhartmann** [comment]
Here's the output when running `/usr/local/bin/gridengine_prometheus --debug --config /etc/gridengine_prometheus/config.yaml` 

Error: 

```Shell
INFO[0000] Getting ready to start exporter on port 9081
ERRO[0005] An error occurred during execution of the the binary /myorg/uge/8.5.5/bin/lx-amd64/qstat. Execution details are error: unable to send message to qmaster using port 6444 on host "ugem-research-dev.myorg.org": got send error

ERRO[0005] There was an error processing the XML output  error="an error occurred during execution of the the binary /myorg/uge/8.5.5/bin/lx-amd64/qstat. Execution details are error: unable to send message to qmaster using port 6444 on host \"ugem-research-dev.myorg.org\": got send error\n. Error: exit status 1"
```

Not sure where it's getting port 6444 from...

**Comment by shairozan** [comment]
Port 6444 may just be a default we work with. What port is your qmaster running with?

**Comment by shairozan** [comment]
```yaml
test: false
port: 9081
pidfile: "/var/run/gridengine_prometheus.pid"
sge:
  arch: "lx-amd64"
  cell: "default"
  execd_port: 6445
  qmaster_port: 6444
  root: "/opt/sge"
  cluster_name: "p6444"
```

The config file that comes in the scripts provides this as a starting point. May just need to update the config to have the appropriate qmaster port details etc

**Comment by tfhartmann** [comment]
But the [config I'm using ](https://github.com/metrumresearchgroup/gridengine_prometheus/issues/30#issuecomment-1817529695)should override that shouldn't it?

**Comment by shairozan** [comment]
It definitely should. I'll make sure nothing wonky is going on with Viper (which is processing all of that via mapstructures)

**Comment by shairozan** [comment]
Oh man, the way viper / cobra are setup here is old school. Going to try to clean this up and make it easier to manage. Will be able to verify given a configuration file to make sure that the environment is getting set correctly before cmd execution

**Comment by shairozan** [comment]
https://github.com/metrumresearchgroup/gridengine_prometheus/releases/tag/v0.0.14-rc3

I did some rework for viper and verified that pointing it at a config reads the expected values out. Let's give this a shot and see what results you get.

**Comment by tfhartmann** [comment]
Oh hey! The metrics endpoint looks like it has some metrics! I still get this error : 

```Shell

ERRO[0005] There was an error extracting Free Memory from the resource list  error="Could not located the requested key"
ERRO[0005] There was an error extracting Used Memory from the resource list  error="Could not located the requested key"
ERRO[0005] There was an error extracting CPU Utilization from the resource list  error="Could not located the requested key"
ERRO[0005] There was an error extracting Free Memory from the resource list  error="Could not located the requested key"
ERRO[0005] There was an error extracting Used Memory from the resource list  error="Could not located the requested key"
ERRO[0005] There was an error extracting CPU Utilization from the resource list  error="Could not located the requested key"
```

but now see some metrics , like `sge_load_average` although the value is `0` (I'm guessing from the above error) but hey, PROGRESS! :woot:

**Comment by shairozan** [comment]
I can see from the gist that the keys we're looking for are present in the XML output, but not for every host. It's essentially trying to iterate over every host to get the details, but host `broad@devuger-c001.broadinstitute.org` does not provide any of the keys used for this. The other hosts however appear to. 

It's probably just erroring that it couldn't extract them for a single host across multiple iterations

**Comment by tfhartmann** [comment]
Sweet!  I think we'll be good to go once you cut a new release! Thanks so much for all the help @shairozan

**Comment by shairozan** [comment]
No problem @tfhartmann I've got a PR out for the underlying serialization library. Once it gets merged, I'll cut a production release for it, re-target this branch to use the production release and then finalize the PR here. I'll shoot you a link with the production release once it's out

**Comment by shairozan** [comment]
Hey @tfhartmann try https://github.com/metrumresearchgroup/gridengine_prometheus/releases/tag/v0.0.14. Just got release v0.0.14 cut

**Comment by tfhartmann** [comment]
@shairozan  I think the RPM will error because the version number went *down* i.e  v0.1.13  -> v0.0.14  any chance you could cut it as v0.1.14 ?

**Comment by shairozan** [comment]
@tfhartmann Sure thing

https://github.com/metrumresearchgroup/gridengine_prometheus/releases/tag/v0.1.14

Sorry about that

**Comment by tfhartmann** [comment]
I'll give this a try!

**Comment by tfhartmann** [comment]
Thanks so much, this fixes me right up!
