### ISSUE TITLE
Create separate labels for host and queue

### ISSUE THREAD

**Issue by shairozan** [metrumresearchgroup/gridengine_prometheus#6]
ATM, queue is part of hostname and label_replace must be used. It would be cool to have 2 separate labels: queue, hostname.

Previously we were just splitting on the hostname, and are currently only taking the hostname. Would be good for the sake of carving up metrics to provide both as labels.

**Comment by shairozan** [comment]
In branch hosts_and_queues. Only caveat I've had to do is that queues would only exist on running jobs. Everything else we force the hostname by electing the hostname of the master / head node. In this scenario pending jobs will have a "pending" queue as it's required by the collector struct for the job.

**Comment by shairozan** [comment]
@dohnto This is ready in a branch called hosts_and_queues. Every stat now has a host / queue split on it. The only thing we had to deal with because of it is pending jobs. They don't technically have a queue so we enforce "pending" as the queue name.

**Comment by dohnto** [comment]
Looks good. I think you can merge/create merge request.

**Comment by shairozan** [comment]
Merged into develop

**Comment by shairozan** [comment]
Merged into last release
